<a href="https://colab.research.google.com/github/Kusumitha-Muddam/Machine-Learning/blob/main/K_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Student Placement Prediction With KNN**

In [ ]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving placement.csv to placement.csv

In [ ]:
df=pd.read_csv('placement.csv')
df.head()

,StudentID,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks,PlacementStatus
0,1,7.5,1,1,1,65,4.4,No,No,61,79,NotPlaced
1,2,8.9,0,3,2,90,4.0,Yes,Yes,78,82,Placed
2,3,7.3,1,2,2,82,4.8,Yes,No,79,80,NotPlaced
3,4,7.5,1,1,2,85,4.4,Yes,Yes,81,80,Placed
4,5,8.3,1,2,2,86,4.5,Yes,Yes,74,88,Placed

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  10000 non-null  int64
 1   CGPA                       10000 non-null  float64
 2   Internships                10000 non-null  int64
 3   Projects                   10000 non-null  int64
 4   Workshops/Certifications   10000 non-null  int64
 5   AptitudeTestScore          10000 non-null  int64
 6   SoftSkillsRating           10000 non-null  float64
 7   ExtracurricularActivities  10000 non-null  object
 8   PlacementTraining          10000 non-null  object
 9   SSC_Marks                  10000 non-null  int64
 10  HSC_Marks                  10000 non-null  int64
 11  PlacementStatus            10000 non-null  object
dtypes: float64(2), int64(7), object(3)
memory usage: 937.6+ KB

In [ ]:
print(df['PlacementStatus'].value_counts())

PlacementStatus
NotPlaced    5803
Placed       4197
Name: count, dtype: int64

In [ ]:
# target
y=df["PlacementStatus"]

# features
x=df.drop(columns=["PlacementStatus"])

x=x.drop(columns=["StudentID"])

In [ ]:
x.head(2)

,CGPA,Internships,Projects,Workshops/Certifications,AptitudeTestScore,SoftSkillsRating,ExtracurricularActivities,PlacementTraining,SSC_Marks,HSC_Marks
0,7.5,1,1,1,65,4.4,No,No,61,79
1,8.9,0,3,2,90,4.0,Yes,Yes,78,82

In [ ]:
#num_x=x.select_dtypes(include=np.number)
cat_x=x.select_dtypes(exclude=np.number)
cat_x

     ExtracurricularActivities PlacementTraining
0                           No                No
1                          Yes               Yes
2                          Yes                No
3                          Yes               Yes
4                          Yes               Yes
...                        ...               ...
9995                       Yes                No
9996                        No                No
9997                       Yes               Yes
9998                       Yes               Yes
9999                        No                No

[10000 rows x 2 columns]

one-hot Encoding

In [ ]:
x_enc=pd.get_dummies(cat_x)
x_enc

,ExtracurricularActivities_No,ExtracurricularActivities_Yes,PlacementTraining_No,PlacementTraining_Yes
0,True,False,True,False
1,False,True,False,True
2,False,True,True,False
3,False,True,False,True
4,False,True,False,True
...,...,...,...,...
9995,False,True,True,False
9996,True,False,True,False
9997,False,True,False,True
9998,False,True,False,True
9999,True,False,True,False

Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y_enc=le.fit_transform(y)
y_enc

array([0, 1, 0, ..., 1, 1, 0])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x_enc,y_enc,test_size=0.2,random_state=2)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 4)
(2000, 4)
(8000,)
(2000,)

In [ ]:
#SCALING
sc=StandardScaler()
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [ ]:
#MODEL

knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train_scaled,y_train)
y_pred=knn.predict(x_test_scaled)

In [ ]:
#evaluation
acc=accuracy_score(y_test,y_pred)
print(acc)
cm=confusion_matrix(y_test,y_pred)
print(cm)
cr=classification_report(y_test,y_pred)
print(cr)

0.727
[[691 432]
 [114 763]]
              precision    recall  f1-score   support

           0       0.86      0.62      0.72      1123
           1       0.64      0.87      0.74       877

    accuracy                           0.73      2000
   macro avg       0.75      0.74      0.73      2000
weighted avg       0.76      0.73      0.73      2000